[metadata]
name = guessinggame
version = 0.1.0
author = Sean Schulze
author_email = skschulz@ksu.edu
description = A fun guessing game.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/ksu-cc410-fall2026/f26-release-example-SSchulze4
    Bug Tracker = https://github.com/ksu-cc410-fall2026/f26-release-example-SSchulze4/issues
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.9
include_package_data = True

[options.package_data]
guessinggame = py.typed